### ISSUE TITLE
Add a greedy/hybrid tree search option 

### ISSUE THREAD

**Issue by erikcs** [grf-labs/policytree#94]
Policy learning with exact search is only feasible on "medium" sized data. For users who want to use this package on datasets of arbitrary size we should offer a greedy option.

We should also consider automatically dispatching to this greedy solver when |X| passes some threshold, such that first-time users don't unintentionally hit an estimated runtime of 100 hrs+.

**Comment by erikcs** [comment]
What do you @kanodiaayush and @swager think of the following API  `tree_search(X, Y, solver = c("auto", "exact", "greedy")` where `auto` means we dispatch to greedy search when the input dimensions would lead to a problem that takes days to compute (can determine exact threshold based some experiments)

With some flexibility I guess we can consider this a "backwards" compatible release (i.e v2.0 not necessary) as we do not expect "many" users to have run policy_tree with default options on data that takes days to compute...

**Comment by susanathey** [comment]
I think that we'd like to give the user some more control, but help guide them through how to use it with some further documentation and specific examples.  A fully greedy algorithm would be nice because in order to apply, say, rpart to policy learning, there are several steps and people find it hard to code/easy to make a mistake.  However, there would be even more value added to have something between fully optimal and fully greedy, e.g. something that looks one step down the tree (and thus considers interactions among variables) but still runs in reasonable time.  In terms of coding, it would be some work for the user to implement a hybrid algorithm like this, so there would be value from using it.  I am worried that the "auto" doesn't really solve the user's problem, it may be too black box.  An alternative to "auto" would be a helper function that returns some info to the user, combined with documentation that shows examples of what to do in different scenarios.

**Comment by erikcs** [comment]
Ideally a user should  be ready for most scenarios by reading the through a succinct `@example` docstring (some improvements in #95). For whichever solver alternative everyone decides on, fully greedy or hybrid, the intention was that `policy_tree` would elicit a useful warning when "auto" switched from the default ("exact") to the alternative (sorry, this wasn't clear above). The `@example` docstring would have explained both of these to the diligent user.

Regarding the hybrid solver, I think it would be beneficial to know more about which (|n|,p,k) configurations you/users that contacted you, expect for this to be beneficial/feasible? If someone expects this to allow them to throw in say 500 covariates with depth 6: am not sure how that would play out...

**Comment by kanodiaayush** [comment]
I think the docstring and helper functions support the same goal but not sure which is better aesthetically.

WRT what is a good intermediate algorithm. Hmmmmm..... I am not sure I can think up one immediately. 

I have ideas but this might need a literature review. @erikcs do you have any intermediate solutions in mind? Also what specific algorithm do you mean by greedy?

**Comment by kanodiaayush** [comment]
we already have a 'look every so often' option - in my understanding scaling that is going to be the best as it scales smoothly and feels like it will have smooth performance degradation.

Also to Erik's point, would be very useful to understand the specific situation that we are trying to fix.

**Comment by susanathey** [comment]
Basic problem trying to fix--users give up because they cannot compute a depth 3 or 4 tree.  Use cases encountered in the lab include tens of thousands to millions of observations, but weak treatment effect heterogeneity, with dozens of covariates.  We might coach people to use fewer covariates, but reducing the sample size is not a great idea with weak signal. They may need depth of 3-5 in order to allow interactions among covariates.  There should be no problem doing trees of depth up to 6 with a hybrid model.  The algorithm I suggested is that you build a depth-2 policy tree.  Then, prune the level 2 splits, and build two more depth-2 policy trees off of the first split.  Keep going.  This gives you better performance than fully greedy, but scales easily.  You can try another version where you substitute 3 for 2.

**Comment by kanodiaayush** [comment]
Perfect. I independently came up with the exact same algorithm in my head too! this also does allow for smooth scaling exactly as in by subbing 3 for 2.

Thanks!

@erikcs lets talk about how to do this

**Comment by kanodiaayush** [comment]
@susanathey have you seen this idea in some paper which has theoretical performance analysis of this vis a vis the full algorithm since you described it? Perhaps an equivalent for Classification or Regression Trees?

**Comment by susanathey** [comment]
CART is fully greedy (doesn't look ahead to future splits) so the hybrid approach is a direct improvement over it

**Comment by erikcs** [comment]
Sounds good! Just to set expectations on runtime here, say we reduce the "deep" L depth tree to several globally optimal k-depth trees (k < L): k=2 will already hit a long runtime way before a milllion observations, we have a short point of reference table here:

https://github.com/grf-labs/policytree/issues/46#issuecomment-686658293

but, combined with careful `split.step` use and rounding/relabeling it can maybe scale, that's an empirical question!

**Comment by kanodiaayush** [comment]
got it @susanathey just to be clear, in extension to depth 3, the method i have in mind is you always prune except at the root split, but the tree depth you go to to create the root split is variable. another method might be to prune the lower most level only.

**Comment by susanathey** [comment]
I would say a routine should "globally" search to level k and "prune" to level k'<k, these can each be user-specified parameters.

**Comment by susanathey** [comment]
With appropriate split.step or rounding, there is no reason that having millions of observations *needs* to be problem.  If # observations was a problem even after the other optimizations, we could additionally sample.  For example couldn't we downsample but then draw in more observations if considered leaves don't have enough data.  There are simpler options too; we could use a smaller dataset to narrow down to a leading set of trees or to optimize with a more coarse grid, and then use more data to fine-tune things.

**Comment by kanodiaayush** [comment]
noted; how should we aim to do this? it feels like this is sufficient to think of in terms of an improvement paper? Or is this just code optimization?

Regards,

**Comment by susanathey** [comment]
I think this can be code optimization for now--I think Erik should be able to implement it pretty quickly

**Comment by erikcs** [comment]
Ayush I can come over to your place one day and we can have a go at it.

**Comment by kanodiaayush** [comment]
Yes that sounds good!

**Comment by erikcs** [comment]
A simple R implementation of `hybrid_policy_tree` is here: https://github.com/grf-labs/policytree/pull/118

(@kanodiaayush also started a more general C++ version in https://github.com/grf-labs/policytree/tree/hybrid_search, I am fine with the R version for now as it makes zero changes to the existing package)

**Comment by erikcs** [comment]
The suggested approach in #118 is simple to define and implement, and it does not involve "pruning". Compared with the two other ways of building a depth 3 tree using exact depth 2 search, which both involves "pruning", it does better:

[Alternative 1](https://gist.github.com/erikcs/e5cb80f657d960df4d3279efa2291d0d): on avg. #118 gives ~ 30% higher reward

[Alternative 2](https://gist.github.com/erikcs/ad75f9ef2c4196f7e61127904ee2f54d): on avg. #118 gives ~ 90% higher reward
